apiVersion: batch/v1
kind: Job
metadata:
  name: llm-compiler-job-PLACEHOLDER
spec:
  completions: 108
  parallelism: 1
  completionMode: Indexed
  backoffLimitPerIndex: 0  # maximal number of failures per index
  maxFailedIndexes: 1     # maximal number of failed indexes before terminating the Job execution

  # podFailurePolicy:
  #   rules:
  #   - action: Count
  #     onExitCodes:
  #       # containerName: main      # optional
  #       operator: NotIn             # one of: In, NotIn
  #       values: [0]
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: llm-compiler
          image: buildbench/llm_assisted_compilation_k8s:latest
          imagePullPolicy: Always
          env:
            - name: REPO_URL
              value: "PLACEHOLDER_REPO_URL"
            - name: JOB_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.annotations['batch.kubernetes.io/job-completion-index']"            
          volumeMounts:
            - name: nfs-shared
              mountPath: "/app/compiled_repos"
              subPath: "user/"
            - name: nfs-shared
              mountPath: "/app/cloned_repos"
              subPath: "user/Compilation_Benchmark/75/cloned_repos"
            - name: nfs-shared
              mountPath: "/app/compiled_results"
              subPath: "user/"
            - name: nfs-shared
              mountPath: "/app/validation_logs"
              subPath: "user/Compilation_Benchmark/75/"
            - name: repos-cm
              mountPath: /app/config
          resources:
            requests:
              cpu: "10"
              memory: "30Gi"
              ephemeral-storage: "20Gi"
            limits:
              cpu: "20"
              memory: "200Gi"
              ephemeral-storage: "75Gi"
              
      volumes:
        - name: nfs-shared
          persistentVolumeClaim:
            claimName: nfs
        # The volume for ConfigMap
        - name: repos-cm
          configMap:
            name: llm-compiler-repos  # We'll create it from orchestrator.py